print("Giraffe\nAcademy")
print("Giraffe\"Academy")
print("Giraffe\\Academy")
phrase = "Giraffe Academy"
print(phrase.index("G"))
print(phrase)
print(phrase + " is cool")
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.islower())
print(phrase.upper().isupper())
print(phrase.lower().islower())
print(len(phrase))
print(phrase[0])
print(phrase[1])
print(phrase[2])
print(phrase[3])
print(phrase[4])
print(phrase[5])
print(phrase[6])
print(phrase.replace("Giraffe", "Zebra"))